### ISSUE TITLE
Change Iterator to Iterable

### ISSUE THREAD

**Issue by ebolyen** [qiime2/q2-types#101]
Iterator's must return themselves when `__iter__` is called. `DNAIterator` is non-conforming. An `Iterator` is probably overkill as well, an `Iterable` would be perfectly fine.

**Comment by BenKaehler** [comment]
Is this the reason that `DNAIterator` is so painful to use?

For instance,
```
DNAIterator(s for s in chain([first_read], reads))
```
is fine, but
```
DNAIterator(chain([first_read], reads))
```
results in 
```
skbio.io._exception.UnrecognizedFormatError: Cannot write 'fasta' into '/var/folders/k7/pw5fgw5j3fd5kmby0h79924w0000gp/T/q2-DNAFASTAFormat-ltuzpxx9', no chain writer found.
```
Thank you!

**Comment by ebolyen** [comment]
It's not DNAIterator's fault so much as skbio's, but yeah it kind of sucks!
What we could do to make this better is yield from the iterable, then skbio
would always see a generator at least. This would be an easy change to make
while we're fussing with the base class.

On Feb 1, 2017 10:17 PM, "BenKaehler" <notifications@github.com> wrote:

Is this the reason that DNAIterator is so painful to use?

For instance,

DNAIterator(s for s in chain([first_read], reads))

is fine, but

DNAIterator(chain([first_read], reads))

results in

skbio.io._exception.UnrecognizedFormatError: Cannot write 'fasta' into
'/var/folders/k7/pw5fgw5j3fd5kmby0h79924w0000gp/T/q2-DNAFASTAFormat-ltuzpxx9',
no chain writer found.

Thank you!

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/qiime2/q2-types/issues/101#issuecomment-276870815>, or mute
the thread

**Comment by BenKaehler** [comment]
Thanks @ebolyen, that would be great.
