### ISSUE TITLE
Format `SingleEndFastqManifestPhred33` and friends do not validate that files are gzipped

### ISSUE THREAD

**Issue by ebolyen** [qiime2/q2-types#114]
It seems to permit both `.fastq` and `fastq.gz` files as "input" for the manifest format. 

It doesn't look like `FastqGzFormat` used in `SingleLanePerSampleSingleEndFastqDirFmt` (or it's paired variant) verify this fact either. It should reject files that aren't gzipped in it's `sniff` method.

It would be nice to be able to gzip in the transformers from the `.*FastqManifest.*` formats if possible.

**Comment by jairideout** [comment]
User story:

*A user should receive an error when attempting to import non-gzipped fastq files as Casava format.*

*A user should be able to import non-gzipped fastq files and have them gzipped automatically when importing as FastqManifest format.*

**Comment by thermokarst** [comment]
Fixed in #119
