### ISSUE TITLE
Define new `Metadata` transformers

### ISSUE THREAD

**Issue by thermokarst** [qiime2/q2-types#122]
Related to https://github.com/qiime2/qiime2/issues/271
Related to https://github.com/qiime2/qiime2/issues/269

**Comment by thermokarst** [comment]
We currently support transforming `SampleData[AlphaDiversity]` to `Metadata`. Based on a pass through `q2-types` (and discussion in #123), it seems like the following would also be good candidates for viewing as `Metadata`:

- `PCoAResults`
- `FeatureData[Taxonomy]`
- `FeatureData[Sequence]`
- `FeatureData[PairedEndSequence]`
- `FeatureData[AlignedSequence]`

The `FeatureData[.*Sequence.*]` transformers would address https://github.com/qiime2/q2-feature-table/issues/104.

**Comment by ebolyen** [comment]
These seem about right to me. Pinging @ElDeveloper again on `PCoAResults`.

Would we have a `forward` and `reverse` column for `FeatureData[PairedEndSequence]`? (Also is there anything that actually uses that yet?)

**Comment by thermokarst** [comment]
@ebolyen, good question re: `FeatureData[PairedEndSequence]`. I just `ag`ed for that across the ecosystem, I'm not seeing anything besides the type definition. Cruising through historic docs, it looks like this was used in `q2-feature-classifier` back in the 2.0.6 days! So maybe we drop `FeatureData[PairedEndSequence]` from this list?

- `PCoAResults`
- `FeatureData[Taxonomy]`
- `FeatureData[Sequence]`
- `FeatureData[AlignedSequence]`

**Comment by thermokarst** [comment]
Thanks @ElDeveloper! Here is a quick `repr` of the dataframe that @nbokulich was proposing in #123 :

```
        unweighted-unifrac-pc1  unweighted-unifrac-pc2  unweighted-unifrac-pc3
L1S105               -0.560048                0.045204                0.015025
L1S140               -0.577116                0.049525                0.018286
L1S208               -0.568779                0.055607                0.011785
L1S257               -0.517907                0.043428                0.005202
...
```

Does this look okay to you? @nbokulich, want to comment as well?

**Comment by nbokulich** [comment]
Thanks @thermokarst and @ElDeveloper ! Yes, that example looks like what I had in mind.
