### ISSUE TITLE
disallow duplicate sample IDs in demux types/formats

### ISSUE THREAD

**Issue by jairideout** [qiime2/q2-types#126]
Came up [on the forum](https://forum.qiime2.org/t/duplicate-sample-ids-a-way-to-catch-them-early/738): duplicate sample IDs should be disallowed with types `SampleData[SequencesWithQuality]` and `SampleData[PairedEndSequencesWithQuality]` (the fix would be implemented on those types' transformers).

**Comment by maxvonhippel** [comment]
This can be assigned to me.

**Comment by thermokarst** [comment]
This came up again [on the forum](https://forum.qiime2.org/t/catching-duplicate-ids-redux/1122/9). It looks like this issue still exists for `CasavaOneEightSingleLanePerSampleDirFmt`.
