### ISSUE TITLE
support importing multiplexed seqs containing barcodes

### ISSUE THREAD

**Issue by jairideout** [qiime2/q2-types#142]
Came up on the forum a few times (e.g. [here](https://forum.qiime2.org/t/problems-with-fastq-files-paired-end-without-barcode-file/960/3), [here](https://forum.qiime2.org/t/how-to-prepare-the-barcodes-fastq-gz-file/589), and [here](https://forum.qiime2.org/t/variable-length-barcodes-with-emp-multiplexed-format/628)). Users need to be able to import multiplexed sequence data that contains barcodes in the sequences (we currently support data that has the barcodes extracted in a separate file, i.e. the "EMP protocol multiplexed data"). For now, a workaround is to use QIIME 1's `extract_barcodes.py` to extract the barcodes into their own file.

**Comment by amwalker** [comment]
I have a slight bend on this issue. I have data with indexes of different lengths, so I don't think extract_barcodes.py will work for me. Any thoughts on this? Thanks!

**Comment by thermokarst** [comment]
Hi @amwalker - can you please ask this question over at https://forum.qiime2.org? That is where we provide user support for QIIME 2. Thanks!

**Comment by thermokarst** [comment]
Supporting types added in #163.
