### ISSUE TITLE
Support interleaved fastq files (like from JGI)

### ISSUE THREAD

**Issue by ebolyen** [qiime2/q2-types#147]
**References**
This came up [on the forum](https://forum.qiime2.org/t/how-do-i-import-interleaved-fastq-files/1186/5?u=ebolyen) (specific details in that post) and corresponds to the QIIME 1 script `extract_reads_from_interleaved_fastq.py`.

**Comment by ebolyen** [comment]
Another [forum x-ref](https://forum.qiime2.org/t/creating-manifest-file-for-fastq-files-that-contain-both-forward-and-reverse-reads/2803)

**Comment by colinbrislawn** [comment]
Another [forum x-ref](https://forum.qiime2.org/t/issues-with-import-fastq-files/9189/)
