### ISSUE TITLE
support .bz2 FASTA file with FeatureData[AlignedSequence]

### ISSUE THREAD

**Issue by jairideout** [qiime2/q2-types#170]
**Improvement Description**
It could be handy to support .bz2 FASTA files with `FeatureData[AlignedSequence]` in addition to the current support for uncompressed FASTA files.

**References**
[forum x-ref](https://forum.qiime2.org/t/bz2-featuredata-alignedsequence/3167?u=jairideout)

**Comment by lizgehret** [comment]
Closing this one out since @ebolyen submitted a more general issue addressing the same functionality request [here](https://github.com/qiime2/q2-types/issues/171).
