### ISSUE TITLE
FeatureData[Taxonomy] validator: check for whitespace in accession #s

### ISSUE THREAD

**Issue by nbokulich** [qiime2/q2-types#174]
[forum xref](https://forum.qiime2.org/t/feature-classifier-says-an-identifier-was-not-present-in-the-reference-taxonomy/3423?u=nicholas_bokulich)

Sounds like whitespace in taxonomy IDs may cause errors downstream (in this case, with blast). Info past the white space is being truncated, either in the taxonomy or sequences.

Should add this to FeatureData[Taxonomy] validation.

Should maybe also determine the behavior in FeatureData[Sequence] artifacts. It is possible that scikit-bio just truncates the seq ID at any whitespace, in which case users don't need to modify their fastas prior to import (this is ideal, since some formats like Genbank store taxonomy and metadata in the header line after a whitespace). But a strict rule may be most efficacious.

**Comment by thermokarst** [comment]
Fixed in #219
