### ISSUE TITLE
TSVTaxonomyFormat should check for empty column labels

### ISSUE THREAD

**Issue by thermokarst** [qiime2/q2-types#181]
The [sniffer](https://github.com/qiime2/q2-types/blob/master/q2_types/feature_data/_format.py#L99-L126) currently just checks for the presence header labels, but doesn't ensure that anything beyond the two record header labels are not empty strings.

This recently [came up on the forum](https://forum.qiime2.org/t/gneiss-balance-taxonomy-error/4294).

**Comment by turanoo** [comment]
@thermokarst I'm interested in this. Can you assign me to this issue? Thanks

**Comment by thermokarst** [comment]
@turanoo --- it would be nice to update the `sniff` method referenced above to use the new `_validate_` API (`sniff` has been deprecated). You can see an example of that process in #195.

**Comment by jakereps** [comment]
I can take a stab at this @thermokarst!

**Comment by thermokarst** [comment]
Fixed in #221
