### ISSUE TITLE
DNAFASTAFormat validator is not catching invalid DNA characters

### ISSUE THREAD

**Issue by nbokulich** [qiime2/q2-types#187]
[from the forum](https://forum.qiime2.org/t/feature-classifier-error-in-qiime2-2018-6/4747/16?u=nicholas_bokulich)

Sure enough, that user successfully imported their sequences but the sequences contain gratuitous violations of IUPAC DNA sequence nomenclature! I quote verbatim:

```
>Otu73
CCTACGGGTGGCTGCAGTCGGGAATTTTGGGCAATGGGCGAAAGCCTGACCCAGCAACGCCGCGTGAAGGATGAAATCCC
TCGGGATGTAAACTTCGCAAGATTGFGÂ@«’CT\@G\AgCGGTTAATACACKBTAT'a‘ˆQCGOta«RT“T\FUA≈GCTC
CGGCVAIBTCCGVGKBAGCAGCCGCEG\@aT¡WGWDG√GAGCAAGKGtTGƒVCGATTTACTGGGCGTAAAGGGCGCGTA
GGCGGTCAGCAcA¡WTGAWVTGTGAAATCTCCGFG«TTAACTCGGAAAGGTCAACTGATACTGTGCGACTAGAFT√AO`*EgG«WCAST&OAATTCTCGGTGTAGCGGTGAAATGC«TAAPADAGAGAGGAAC@C«TGCGGKGaEGGCGGGTTGCTGG
GCTGACACTGABG«TGAGGCGCGAAAGCCAGGGGAGCGAACGGGATTAGATCCKBTAGT¡GT
~OtT74
TAGTGCGAGCCTACGGGTGGCTGCAGTCGGGAATTTTGCTCAATGGGGGAEASACTGAAGCAFC≈ACGCCGCGTGCGGGA
TGAAGGCCTTCGGGTTGTAAASCKTTTTACCAGGACfATAATGACGGTACCTGATGAAT¡AGCaGGGTA`CTACGD
KCQGIWACGCGGTAATACGTAGGTGACTAGCGTVG\BCGGATTTACTGGGCGTAAAGAGCGC«CEWAG«TCTTCAA
GTCGAGTGTGAAAGCCCCCGGCTCAACTGGGGAGGuCATTBG≈TACTGATCGACTCGAAGGSAOAGAGGA`GAGO@A
TTCCCGGTGTAGTGGTGAAuGCGTAGAT¡TCGGAGGAACABG≈WVGGCGQAOCGGCTTCCTGCCSVGTTCTTGACGCTWCGCGbGACAOBTAGGGGaG√QAACGGGATTAGATACCCTAGTAGTC‘AGGG
>Otu75
CCTACGGGPGWATGCAGTGAGGAATATTGGTCAATWGKGAGAGCCTGAACCAG√CAgT¡WCGTGCAGGATGABF√«CC
TATGMG|AGIAACTGCTTTTATACAGGAATAAAGTTAGCAbGTGTGWTITTUG–AGGTAC‘GTTGAATAAGGACCG
GCTAATTCCGTGCCAGCAGCCGCGGTAATACGGAAGGTCCAGGCGTTATCCGGATTTATTGGGTTTAAAGGGAGCGTAGG
CCGTCTGTTAAGCGTGTTGTGAAATGTAGATGCTCAACATCTGAATTGCAGCGCGAACTGGCAGACTTGAGTGTGCGCAA
CGTAGGCGGAATTCGTGGTGTAGCGGTGAAATGCTTAGATATCACGAAGAACTCCAATTGCGAAGGCAGCTTACGGGAGC
ACAACTGACGCTGAAGCTCGAAAGTGCGGGTATCGAACAGGATTAGATACCCTAGTAGTC
```

Perhaps I should report this on skbio instead... but I figure I will work backwards. Perhaps skbio has good reason to accept a more flexible range of characters?

**Comment by thermokarst** [comment]
👍 - I can't speak for `skbio`, but the sniffer (the deprecated format validation API) only looks at the [first 5 records](https://github.com/qiime2/q2-types/blob/master/q2_types/feature_data/_format.py#L133-L150). A good sprint topic would be to bolster format validation by dropping the deprecated sniff and checking for more edge cases, generally.

**Comment by nbokulich** [comment]
that must be it — the example I gave occurred beyond the first 5 records.

I've added this to the `2018.8` project board — updating validation is sufficiently important (and I can do it if nobody else can)

**Comment by nbokulich** [comment]
sniff really needs to be updated to validate the full file.

Another edge case: blank lines
[forum xref](https://forum.qiime2.org/t/skbio-io-exception-fastqformaterror-found-blank-or-whitespace-only-line-before-in-fastq-file/4999)

**Comment by turanoo** [comment]
@nbokulich I am interested in this issue! would you be able to assign it to me?

**Comment by Oddant1** [comment]
@nbokulich I've been tinkering with this issue, and I was wondering to what extent we want to validate the files? Are we simply checking for egregious issues like undecodable bytes and blank lines like in those two examples? Or should we verify every line in the file contains only valid characters for that line? The second is fully doable, but it is obviously somewhat time-consuming especially for large files. All the same, it seems like something that should be done immediately instead of allowing for importing of broken data only to have the user find out later (like in the examples this issue originated from!) that their data is garbage in some way.

**Comment by nbokulich** [comment]
> Are we simply checking for egregious issues like undecodable bytes and blank lines like in those two examples?
We want to check for invalid characters (valid characters [‘G’, ‘W’, ‘R’, ‘M’, ‘K’, ‘B’, ‘V’, ‘A’, ‘-’, ‘.’, ‘D’, ‘C’, ‘T’, ‘H’, ‘S’, ‘N’, ‘Y’]). maybe we should just use scikit-bio's FASTA validator if there is one...

> but it is obviously somewhat time-consuming especially for large files.
I agree line-by-line validation may be too slow — is there a faster way to do this?

> it seems like something that should be done immediately instead of allowing for importing of broken data only to have the user find out later
I have mixed feelings on this. On the one hand, it would be good to warn users at import if their data quality is poor. But unless if the validator is very quick, this will be too much of a headache (e.g., each time we import a massive reference sequence file that _should_ already be clean). If the validator is not quick, make this something that users would optionally do after importing.

**Comment by thermokarst** [comment]
The validation API supports validation at two levels (`min` & `max`). `min` is used everywhere by default, and is expected to go somewhat fast. If a user encounters a true issue, they can use `qiime tools validate $ARTIFACT` if they run into a problem --- this will validate on `max`. It is up to you how you split up `min` and `max`, but, for the FASTQ format (a similar type of format), [we check the ](https://github.com/qiime2/q2-types/blob/03a15c2c8682d03f367564cf126e20f9e3672cd0/q2_types/per_sample_sequences/_format.py#L232-L279)first 5 records on `min`, and the entire file on `max`. Another strategy could be to always check _all_ the records in the file (on both `min` and `max`), but add in additional validations when `max` is specified. YMMV.

Please note, the `DNAFASTAFormat` is using the now-deprecated `sniff` API, which the validation API replaced.

**Comment by Oddant1** [comment]
> Another strategy could be to always check all the records in the file (on both min and max), but add in > additional validations when max is specified. YMMV.

I created a 4 gig text file by copy-pasting the data referenced in [the forum thread](https://forum.qiime2.org/t/feature-classifier-error-in-qiime2-2018-6/4747/16) referenced in the issue and, on my laptop anyway, it took 55 seconds just to run 
```
for line in file:
    pass
```
Actual validation of each line added ~10 seconds. Given that, I'm not sure it would be worth going through the entire file at all on import if we're particularly concerned about import times. Unless somewhere in the vicinity of a minute for a file that large is acceptable. All the same, I'm leaning more towards thinking the first option and what @nbokulich said is the best idea. Scanning some set amount of sequences on import then allowing for validation of the entire file later. These times scale less than linearly, with ~160mb files taking around 2.5 seconds to validate. Note, all of these numbers are validation on import of a text file not validation of an already existing .qza

> for the FASTQ format (a similar type of format), we check the first 5 records on min, and the entire file > on max

I notice this code doesn't ensure the sequences contain only valid characters. Is this something we're interested in for FASTQ files as well?

**Comment by nbokulich** [comment]
@thermokarst isn't this the DNAFASTAFormat sniff in question? 
https://github.com/qiime2/q2-types/blob/03a15c2c8682d03f367564cf126e20f9e3672cd0/q2_types/feature_data/_format.py#L133

> Another strategy could be to always check all the records in the file (on both min and max), but add in additional validations when max is specified.

I am warming to this idea, because we know that `validate` is not widely used by your average Joe.

Could we just use a `grep` subroutine to scan non-header lines for invalid characters for `min` validation? That would be faster than a python line-by-line validation, and we could leave more serious validation for `max`.

**Comment by thermokarst** [comment]
> All the same, I'm leaning more towards thinking the first option and what @nbokulich said is the best idea. Scanning some set amount of sequences on import then allowing for validation of the entire file later

This is the strategy that most of our formats use now (as I mentioned about with the FASTQ example). It sounds like @nbokulich might be more in favor of the "always validate the whole file, just to different degrees" strategy, though.

> I notice this code doesn't ensure the sequences contain only valid characters. Is this something we're interested in for FASTQ files as well?

No, let's keep the focus on the FASTA format(s).

---

> @thermokarst isn't this the DNAFASTAFormat sniff in question?

Yep, @nbokulich. Why do you ask? `sniff` should be replaced with `_validate_`.

> Could we just use a grep subroutine to scan non-header lines for invalid characters for min validation?

I would prefer not to, unless you want to add `grep` as a conda dep (assuming it is available).

**Comment by nbokulich** [comment]
> Why do you ask? sniff should be replaced with _validate_.

just wanted to make sure, since you linked to the fastq format above (was not reading closely enough, now see you were just giving an example)

> I would prefer not to, unless you want to add grep as a conda dep (assuming it is available).

darn. Guess we don't want to add a dep but [it is there](https://anaconda.org/bioconda/grep). Alternatively, [this SO answer](https://stackoverflow.com/questions/38916645/python-grep-code-much-slower-than-command-lines-grep) has a python implementation that is only a little slower than grep.

> It sounds like @nbokulich might be more in favor of the "always validate the whole file, just to different degrees" strategy, though.

I am just leaning in that direction, but I am like a broken fence post and lean whichever way the wind blows.
