### ISSUE TITLE
zipped fasta gets imported and fails silently

### ISSUE THREAD

**Issue by BenKaehler** [qiime2/q2-types#194]
**Bug Description**
zipped fasta gets imported and fails silently

**Steps to reproduce the behavior**
1. gzip a fasta file
2. `tools import --type FeatureData[Sequence]` it
3. unzip the archive and observe the horror

**Expected behavior**
It would have been super-nice if import noticed that the file was zipped and unzipped it

**Computation Environment**
- OS: linux of some sort
- QIIME 2 Release 2018.4

**Comment by lizgehret** [comment]
This has been addressed - [PR xref](https://github.com/qiime2/q2-types/pull/244#issuecomment-634112153) mentioning the resolution.
