### ISSUE TITLE
Differential type

### ISSUE THREAD

**Issue by mortonjt** [qiime2/q2-types#211]
**Improvement Description**
In differential abundance analysis, the regression coefficients learned carry relative information about them, which can allow users to infer which microbes are increasing / decreasing the most relative to each other.

In Songbird, we have defined a `Differential` type to encapsulate these parameters learned from a multinomial model.  However, this is not unique to Songbird and applies to almost every existing differential abundance method, including ALDEx2, DESeq2 and edgeR.

**Current Behavior**
There is a Composition type, but this really is not applicable given the dense nature of the data type.

**Proposed Behavior**
I propose to move this type to the core q2 types in order to avoid duplication of types.
The songbird type definition can be found here: https://github.com/biocore/songbird/blob/master/songbird/q2/_stats.py#L20

Ultimately, this will be a type representing a table of regression coefficients, where each row corresponds to a feature (i.e. microbe) and every column corresponds to a metadata category.  This table is expected to be very small, but dense - so a text / metadata format is preferable.

It'll also make it easier to standardize incoming differential abundance techniques.  Here, we have an incoming aldex2 plugin: https://github.com/mortonjt/q2-aldex2 

So, the release of this plugin is contingent on getting this type in the core types.

**Comment by ebolyen** [comment]
fixed in #212
