### ISSUE TITLE
Move matplotlib pin to >=3.2

### ISSUE THREAD

**Issue by ChrisKeefe** [qiime2/q2-types#232]
**Bug Description**
In response to [this issue](https://github.com/qiime2/q2-sample-classifier/issues/164), we hard-pinned `matplotlib` and `matplotlib-base` to `3.1.0`. Version `3.2` should remedy the issue, but was not available at release time. 

This hard pin prevents conda from using newer versions of matplotlib.

**Fix**
We should move both mpl pins to >= 3.2.0

**Expected behavior**
This will allow conda to build with up-to-date mpl, while avoiding bugs in older versions.

**Comment by Oddant1** [comment]
As of February 12th 2020, the latest stable release of matplotlib is 3.1.3, and 3.2.0 is available as a preview release.

**Comment by thermokarst** [comment]
@Oddant1, have you checked to see if 3.1.3 includes a fix to the issue that @ChrisKeefe mentioned? It might be the case that we don't need to wait for 3.2.0 if the fix is in 3.1.3.
