### ISSUE TITLE
new format / transformer for single-end demuliplexed files named by sample id

### ISSUE THREAD

**Issue by gregcaporaso** [qiime2/q2-types#286]
A manifest is overkill if it looks like the following:

```
sample-id    absolute-filepath
sample-1    $PWD/sample-1.fastq.gz
s2    $PWD/s2.fastq.gz 
xyz    $PWD/xyz.fastq.gz
```

I came across this working with a colleague recently. A directory format and transformer to support direct import of these data will support easier and better importing.

**Comment by ebolyen** [comment]
closed by #287
