### ISSUE TITLE
support import/demux of fastq with barcode in the header line

### ISSUE THREAD

**Issue by nbokulich** [qiime2/q2-types#302]
**References**
1. Came up on the [forum](https://forum.qiime2.org/t/how-to-import-data-from-miseq-paired-end-reads-2-x-251/2204).
2. Another case covered by [`extract_barcodes`](http://qiime.org/scripts/extract_barcodes.html) in qiime1.

**Comment by lizgehret** [comment]
Nice write-up on this one [here](https://github.com/qiime2/q2-types/issues/300). Closing this one (even though this was opened first) since we have more details on the newer issue submission.
