### ISSUE TITLE
Blast6 file empty

### ISSUE THREAD

**Issue by fabio-marcelo** [qiime2/q2-types#304]
Hi everyone.
I've run qiime feature-classifier classify-consensus-blast  inside docker container quay.io/qiime2/core:2023.7
 and I've got the error Blast6 file is empty. 
I changed the version of taxonomy and ref files but keep throwing the same error.

qiime tools import \
--type FeatureData[Sequence] \
--input-path sh_refs_qiime_ver9_99_s_all_29.11.2022.fasta \
--output-path reference_sequences.qza 

qiime tools import \
--type FeatureData[Taxonomy] \
--input-path sh_taxonomy_qiime_ver9_99_s_all_29.11.2022.txt \
--output-path reference_taxonomy.qza \
--input-format HeaderlessTSVTaxonomyFormat

qiime feature-classifier classify-consensus-blast \
--p-perc-identity 0.99 \
--i-query representative-seqs.qza \
--i-reference-reads reference_sequences.qza \
--i-reference-taxonomy reference_taxonomy.qza \
--o-classification blast-taxonomyITS.qza \
--output-dir temp/blast

Any ideia?

**Comment by nbokulich** [comment]
Hi @fabio-marcelo , please post all user support questions to the QIIME 2 user forum: forum.qiime2.org/

Thank you!
