### ISSUE TITLE
MAINT: Migrate q2-types-genomics types/formats/transformers into q2-types

### ISSUE THREAD

**Issue by lizgehret** [qiime2/q2-types#308]
All of the types/formats/transformers from q2-types-genomics should be moved into q2-types. This will provide a more unified location for all of the types/formats/etc that we use in QIIME 2, and will also allow for RESCRIPt to be added to the amplicon distribution (since this is currently blocked by the fact that RESCRIPt depends on q2-types-genomics).

There are a couple of shared type families in types and types-genomics:

- feature-data (named as such in both repos)
- per-sample-sequences (named as such in types, and per-sample-data in types-genomics)

Everything that exists under these type families in types-genomics should be moved into the corresponding type family dir by adding those types/formats/etc into the appropriate files.

The other type families that exist solely in types-genomics should just be moved over to types wholesale (i.e. `genome_data`, `kaiju`, `kraken2`, etc).

The same principle applies for the tests associated with all of the types/formats/etc in types-genomics.

A few helpful reminders/to-do's:
- Adding the data dirs for any test data into setup.py so they are accessible to the GHA runners when CI is running the test suite.
- Adding all necessary imports into the relevant __init__.py files.
- Adding any dependencies from types-genomics' recipe file that aren't present in types.

**Comment by Oddant1** [comment]
@lizgehret merging the two feature-data folders proved a bit painful, so I renamed the feature-data from types-genomics to feature-data-mag for now. I'll take a crack at merging per-sample-sequences and maybe another at feature-data tomorrow.
