### ISSUE TITLE
Patch to work with Pandas 2.x

### ISSUE THREAD

**Issue by tillea** [qiime2/q2-types#310]
**Improvement Description**
The code of version 2023.9.0 has some conflict with Pandas 2.x

**Current Behavior**
There are test suite errors with Pandas 2.x

**Proposed Behavior**
In the Debian packaged version of q2-types we include a [patch](https://salsa.debian.org/med-team/q2-types/-/blob/master/debian/patches/pandas-2.0.patch?ref_type=heads) that fixes the issue.  Feel free to take over this patch.

Hope this helps, Andreas.

**Comment by gregcaporaso** [comment]
q2-types is now working with pandas 2.2.2. This update will be included in the upcoming 2024.5 release (coming later this month).
