### ISSUE TITLE
FEAT: Importing sequence data from BIOM files

### ISSUE THREAD

**Issue by peterjc** [qiime2/q2-types#315]
This based on the discussion at https://forum.qiime2.org/t/how-to-import-a-biom-file-containing-sequences/29452/7 where filing an issue was suggested, along side background reading including https://forum.qiime2.org/t/feature-table-filter-samples-removes-taxonomy-from-biom-table/1159/3 which talks about the need to do multiple imports of a single "fat" BIOM format to extract different interpretations of it (like ``FeatureTable[Frequency]`` and ``FeatureData[Taxonomy]``).

**Addition Description**

BIOM files at their core are a table of sequence identifiers (OTUs or ASVs) versus samples, with a matrix of counts. There can be metadata for each sample (e.g. location, host) and for each sequence (e.g. taxonomic classification, or sequence).

My understanding is a ``FeatureTable[Frequency]`` import extracts just the core counts array (per sequence per sample), while a ``FeatureData[Taxonomy]`` import looks for any taxonomic classification of the sequences.

I want to be able to import any amplicon sequence data in the BIOM file into Qiime2, as a ``FeatureData[Sequence]`` import or similar.

**Current Behavior**

Import of ``FeatureData[Sequence]`` from BIOM is not currently supported. The workaround is to convert the BIOM file to FASTA, and import that.

**Proposed Behavior**

I would like to be able to run:

```
$ qiime tools import \
  --input-path hdf5.biom \
  --output-path feature-seqs.qza \
  --type "FeatureData[Sequence]"
```

This should look at the metadata for a suitable column of strings, e.g. check names "Sequence", "sequence", "seq" or similar.

**Questions**

1. Must we do separate imports of a "fat" BIOM, rather than importing it once into a composite capturing all the reasonable Qiime interpretations?
2. Is there an nice way to take additional arguments (like the name of the BIOM metadata column)?
3. Is it worth handling the special case where the sequence itself is used as the identifier?

**References**
1. https://forum.qiime2.org/t/how-to-import-a-biom-file-containing-sequences/29452/7
2. https://forum.qiime2.org/t/feature-table-filter-samples-removes-taxonomy-from-biom-table/1159/3

**Comment by gregcaporaso** [comment]
@peterjc, this is definitely possible to do and is fairly straight-forward. I haven't seen biom files like these very often in the wild - is this common for biom files from some specific source? And do you have a small example file (e.g., a couple of samples and a few features)?

The way to do this would be to define a transformer or two (for different versions of the biom format) similar to the [biom to taxonomy ones](https://github.com/qiime2/q2-types/blob/823b5a4411938fcc2f3af6bfdb96dab3745f4aaa/q2_types/feature_data/_transformer.py#L220). Those could live in that sample file, and most likely would translate to a `pd.Series`, and maybe directly to `DNAFASTAFormat` (but QIIME 2 can also take care of the `pd.Series` to `DNAFASTAFormat` transformation, albeit a little slower than if there is a direct transformer). 

From your first forum post it sounds like you have a work-around so you're not blocked on this. I may queue this one up for a series of how-to videos I'm planning on QIIME 2 development for our YouTube channel.

**Comment by peterjc** [comment]
These "fat" BIOM files are from my own pipeline - https://github.com/peterjc/thapbi-pict

I wanted a single intermediate file combining the ASV vs samples counts (the main part of a BIOM file) with derived sample-metadata (e.g. raw read counts per sample) and the ASV sequences themselves. I was actually surprised the BIOM format didn't have a recommended metadata field name to use for that.

As you noticed from the forum, I can work around this by exporting the BIOM file with a matching FASTA file, and importing those two into Qiime2.

As to a test case, I don't seem to have any checked into version control in BIOM v2.1 format - I was worried about no promise of binary identity, so instead validate my output via the biom command line tool. I also have multiple worked examples from which I could export a BIOM file very easily - they might be a little on the large size.

Would uploading a small example BIOM file to this issue suffice?

**Comment by gregcaporaso** [comment]
Yep, small example uploaded here would work. Ideally it could be one that has no confidential information, so it could be used in the video content I described above (which would likely make the file available for a user who wanted to follow along).

**Comment by peterjc** [comment]
Is 122 samples and 57 denoised ASVs too big?

This example uses the raw data from:

> Riddell et al. (2019) Metabarcoding reveals a high diversity of woody host-associated Phytophthora spp. in soils at public gardens and amenity woodlands in Britain. https://doi.org/10.7717/peerj.6931

This is based on my tool's worked example https://thapbi-pict.readthedocs.io/en/latest/examples/woody_hosts/index.html (page source at https://github.com/peterjc/thapbi-pict/tree/master/examples/woody_hosts including scripts). Currently that doesn't bother with BIOM output, or denoising.

The files below were generated with:

```console
$ thapbi_pict --version
THAPBI PICT v1.0.12
$ flash --version | head -n 1
FLASH v1.2.11
$ cutadapt --version
4.4
$ ./setup.sh  # see link above, downloads the FASTQ files
...
$ thapbi_pict prepare-reads -i raw_data/ -o intermediate/
Looking for 1 markers in 122 samples
...
$ thapbi_pict sample-tally  --synthetic "" \
    -i intermediate/ITS1/*.fasta \
    -n intermediate/ITS1/NEGATIVE_*.fasta \
    --denoise unoise-l \
    -o woody-hosts-example.tsv \
    --biom woody-hosts-example.biom \
    --fasta woody-hosts-example.fasta
...
$ ls woody-hosts-example.*
woody-hosts-example.biom  woody-hosts-example.fasta  woody-hosts-example.tsv
```

The BIOM and FASTA should be equivalent to what https://github.com/peterjc/q2-thapbi-pict v0.0.1 would offer. The TSV forces the per-sample metadata into additional header lines (the main table is easily parsed by skipping the first lines).

To try to keep this on the small side, it has been denoised with UNOISE2 (my implementation) to nearly halve the number of ASV versus no denoising. Using UNOISE3 via USEARCH or VSEARCH is very slightly more agressive.

The BIOM file has just the sequence as observation metadata, but a bunch of fields for each sample like the raw FASTQ read count:

```console
$ biom summarize-table -i woody-hosts-example.biom | head -n 25
Num samples: 122
Num observations: 57
Total count: 602716
Table density (fraction of non-zero values): 0.064

Counts/sample summary:
 Min: 0.000
 Max: 19900.000
 Median: 4637.000
 Mean: 4940.295
 Std. dev.: 2813.004
 Sample Metadata Categories: Control; Cutadapt; Flash; Raw FASTQ; Singletons; Threshold; Threshold pool
 Observation Metadata Categories: Sequence

Counts/sample detail:
NEGATIVE_firstplate: 0.000
NEGATIVE_secondplate: 0.000
Site_13_sample_7: 0.000
Site_9_sample_4-3: 0.000
Site_5_sample_2: 1324.000
Site_8_sample_7: 1430.000
Site_12_sample_1: 1626.000
Site_11_sample_2: 1786.000
Site_5_sample_6: 1947.000
Site_2_sample_5: 2055.000
```

[woody-hosts-example.zip](https://github.com/qiime2/q2-types/files/14616287/woody-hosts-example.zip)

I could cut this down further (e.g. use half the sampled sites) if you'd prefer?

**Comment by gregcaporaso** [comment]
This should work fine, thanks @peterjc. I'll cite the Riddell et al. (2019) paper where I use this table. I'm planning to make a few videos for my developer video series by May 1 for a deadline I have, so this should be available on that timeframe.
