### ISSUE TITLE
IMP: PacBio Phred Offset is Incorrectly Translated

### ISSUE THREAD

**Issue by hagenjp** [qiime2/q2-types#329]
**Improvement Description**
 PacBio Phred offset is not in range of Phred33

**Current Behavior**
Currently PacBio sequences will import out of range 

**Proposed Behavior**
Sequences will be imported in range resulting in improved analysis and readability of interactive quality plot 

**References**
https://forum.qiime2.org/t/hifi-16s-analysis/30165/4
https://forum.qiime2.org/t/dada2-denoising-ccs-error-in-learning-error-rates/30188/11

**Comment by gregcaporaso** [comment]
Closed by qiime2/q2-demux#162
