### ISSUE TITLE
add format for QIIME 1 demultiplexed fastq

### ISSUE THREAD

**Issue by gregcaporaso** [qiime2/q2-types#39]
**Comments**
this will simplify importing data from QIIME 1.

**Comment by mortonjt** [comment]
Hi @gregcaporaso couple questions

1. Is this to address already demultiplexed samples?
2. Is there an easy way to look up the available types in a help menu.  Its not intuitive how to do this without digging into the source code atm.

**Comment by gregcaporaso** [comment]
1. It would, but now that we have the `q2-demux` plugin I'm not so sure that this is necessary. 
2. No, not yet. It's planned, but we haven't got to it yet. If you're looking for a type, just ping us on Slack with a question - we'll handle it that way for now.

**Comment by jairideout** [comment]
There isn't an automated generation of available types, but I updated the semantic types page for the 2.0.5 train release and we'll do our best to keep it updated with future releases:

http://2.qiime.org/docs/semantic-types.html

**Comment by gregcaporaso** [comment]
Sorry, forgot about that page!

**Comment by jairideout** [comment]
[Came up on the forum](https://forum.qiime2.org/t/qiime1demuxformat-is-not-compatible-with-fastq-files/1603?u=jairideout).
