### ISSUE TITLE
detect and support phred offsets other than 33

### ISSUE THREAD

**Issue by jairideout** [qiime2/q2-types#98]
**Bug Description**
The current directory formats assume the phred offset is 33, but this is not always the case. Labeling as a bug since it is possible to create a phred offset 33 directory format with phred offset 64 data, and no error is displayed until quality scores are requested in a transformer (e.g. loading into skbio Sequence objects).

**References**
Original issue reported [here](https://github.com/qiime2/docs/issues/60).

**Comment by gregcaporaso** [comment]
This is now handled for demultiplexed data (via #111), but the issue is still possible with multiplexed data. Re-opening this, as we need to handle it for multiplexed data as well.

**Comment by lizgehret** [comment]
Will re-open this if this ever comes up as a more common issue on the user forum.
