### ISSUE TITLE
Super type for Phylogeny

### ISSUE THREAD

**Issue by mortonjt** [qiime2/q2-types#99]
Right now Phylogeny implies that it will only be allowed to handle phylogenetic trees.  But there are many tree like structures that could be made - for instance hierarchical clusterings.

Could we create a super type, for example `Hierarchy` that could encompass both Phylogenies and Clusterings?

**Comment by jairideout** [comment]
👍, I think a new semantic type for this makes sense. Haven't thought about naming too much, maybe something like `Network` or `Graph`? We could also define more specific graph types in the future (e.g. DAGs).

We'd want to keep `Phylogeny[Rooted]` and `Phylogeny[Unrooted]` around for methods that expect these specific graph types. I'm not sure if the generic graph type and `Phylogeny` would necessarily be related in terms of sub/super-types though -- what sort of structuring were you thinking of? Something like `Graph[Phylogeny[Rooted]]`?

**Comment by mortonjt** [comment]
Cool!  

I think that the graph types make sense.  Although for the use case that I'm considering, I just want to give a semantic meaning to trees other than just phylogeny.  So having some generic Tree type other than a phylogeny I think would be semantically useful.  For instance, I have a few methods in gneiss that implement [hierarchical clusters](https://github.com/biocore/gneiss/blob/master/gneiss/tree/_pba.py) that are represented by trees, but aren't actually phylogenies.

I'm about to push out a q2 plugin into gneiss, implementing a whole bunch of q2 types to play around with the semantic types.  Will give an update once a PR is in.

**Comment by jairideout** [comment]
Sounds good, looking forward to checking out the new types!

**Comment by jairideout** [comment]
@jakereps did you close this by accident? :shipit:

**Comment by jakereps** [comment]
I guess I did... Oops!

**Comment by jairideout** [comment]
No problem, thanks for reopening!

**Comment by jairideout** [comment]
Fixed in #112.
